let customers = [
    {
        id: 1,
        name: "Naveen",
        description:
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla minus, eius iste suscipit nobis, rem atque minima eveniet officiis maiores expedita. Delectus odit, consequatur et ullam sit, voluptatem quas vitae laboriosam, incidunt ex soluta?",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "-$270.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 2,
        name: "Aisha",
        description:
            "Quisquam velit doloribus minima, nostrum quos fugit molestias consectetur ad soluta iste rerum adipisci quaerat, tenetur optio. Amet, suscipit eveniet?",
        status: "paid",
        rate: "$85.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 3,
        name: "Carlos",
        description:
            "Dignissimos hic laborum rem voluptas. Expedita consequuntur at veritatis sequi? Nemo, quae quam! Necessitatibus doloribus rerum exercitationem nulla.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$750.00",
    },
    {
        id: 4,
        name: "Sophie",
        description:
            "Eaque facilis perferendis voluptas sit quibusdam voluptatibus nobis ipsam aliquid, quia voluptates fugit minus unde modi deserunt quam.",
        status: "inactive",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$320.00",
        phoneNumber: "9877565656",
        deposit: "$1200.00",
    },
    {
        id: 5,
        name: "Liam",
        description:
            "Repellat quam laboriosam soluta facere voluptatem voluptate ratione, temporibus accusamus quis reprehenderit voluptates doloribus atque obcaecati quae esse.",
        status: "open",
        rate: "$75.00",
        currency: "CAD",
        balance: "$0.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 6,
        name: "Emma",
        description:
            "Temporibus expedita molestiae, commodi magni corporis voluptate repellat sapiente odio ratione!",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 7,
        name: "Oliver",
        description:
            "Alias magni quisquam at debitis quibusdam asperiores ea soluta optio.",
        status: "inactive",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 8,
        name: "Ava",
        description:
            "Maxime quidem natus error saepe pariatur amet eveniet doloremque quae.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$400.00",
    },
    {
        id: 9,
        name: "William",
        description:
            "Accusantium quam obcaecati, pariatur assumenda numquam vel.",
        status: "paid",
        rate: "$60.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 10,
        name: "Isabella",
        description: "Voluptatibus dolorum id nesciunt veritatis adipisci!",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 11,
        name: "James",
        description:
            "Sapiente nemo magnam possimus laudantium officiis consectetur.",
        status: "inactive",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$750.00",
    },
    {
        id: 12,
        name: "Sophia",
        description:
            "Doloribus officiis aspernatur nisi rem aperiam ea optio voluptatum.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 13,
        name: "Benjamin",
        description: "Consequatur rem voluptas minus fuga eligendi nulla.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$250.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 14,
        name: "Mia",
        description:
            "Adipisci soluta voluptatem aliquid quam numquam repellat iure.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 15,
        name: "Lucas",
        description:
            "Voluptatem repudiandae officia perferendis exercitationem accusamus veniam.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 16,
        name: "Amelia",
        description:
            "Harum necessitatibus facilis veritatis distinctio nulla odit.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 17,
        name: "Henry",
        description: "Laborum impedit nemo maiores exercitationem facere.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 18,
        name: "Evelyn",
        description:
            "Inventore repudiandae suscipit nesciunt harum laboriosam magnam.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 19,
        name: "Alexander",
        description:
            "Eaque ipsa perferendis nesciunt dolor beatae fugit doloremque.",
        status: "due",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 20,
        name: "Harper",
        description: "Ducimus placeat quam dolore explicabo fugit enim.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 21,
        name: "Daniel",
        description: "Voluptate culpa eum facilis quae voluptas.",
        status: "paid",
        rate: "$90.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 22,
        name: "Grace",
        description: "Fugit magnam distinctio omnis accusantium tenetur.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 23,
        name: "Matthew",
        description: "Praesentium ipsum ex minima quibusdam quod.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 24,
        name: "Ella",
        description: "Tempore corrupti voluptas commodi architecto distinctio.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 25,
        name: "Joseph",
        description: "Autem velit dolorem pariatur doloribus.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 26,
        name: "Scarlett",
        description: "Aliquid doloribus sit eos commodi accusamus.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 27,
        name: "David",
        description: "Voluptas rerum suscipit eveniet consectetur minima.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 28,
        name: "Victoria",
        description: "Totam molestias voluptatibus fugit dolores earum.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 29,
        name: "Jackson",
        description: "Quod voluptatem eos consequuntur repudiandae, sint quia.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 30,
        name: "Aria",
        description:
            "Officia reprehenderit doloribus qui voluptatem, voluptas corporis.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 31,
        name: "Samuel",
        description: "Voluptate dolorum fuga explicabo porro.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$250.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 32,
        name: "Madison",
        description: "Repellat accusantium minima alias pariatur ex.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 33,
        name: "Sebastian",
        description:
            "Consequatur exercitationem totam eos recusandae sapiente.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 34,
        name: "Luna",
        description:
            "Autem aperiam doloribus consequatur sit fugiat asperiores.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 35,
        name: "John",
        description:
            "Quibusdam laborum officiis deserunt id, similique adipisci.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 36,
        name: "Hannah",
        description: "Quod temporibus maiores architecto dolores nam cumque.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 37,
        name: "Levi",
        description: "Adipisci doloribus quos non ex repellendus optio.",
        status: "due",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 38,
        name: "Addison",
        description: "Quo voluptatibus deserunt voluptate laudantium suscipit.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 39,
        name: "Isaac",
        description: "Itaque blanditiis veritatis sit doloribus ullam.",
        status: "paid",
        rate: "$90.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 40,
        name: "Zoe",
        description:
            "Beatae asperiores tempore architecto voluptas delectus quasi.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 41,
        name: "Owen",
        description:
            "Voluptatem repudiandae alias nobis deserunt recusandae optio.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 42,
        name: "Lily",
        description: "Sunt dolorem eligendi nisi numquam nulla fuga culpa.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 43,
        name: "Gabriel",
        description:
            "Eius earum reiciendis illum veniam aperiam tempora adipisci.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 44,
        name: "Natalie",
        description:
            "Cum voluptate voluptatum saepe, unde repellendus laudantium!",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 45,
        name: "Wyatt",
        description:
            "Dignissimos, tempora? Aperiam iste veritatis odit veniam alias.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 46,
        name: "Aubrey",
        description:
            "Repudiandae reprehenderit aspernatur atque officia molestiae veritatis.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 47,
        name: "Jack",
        description: "Consequatur rerum impedit nihil quod, officiis libero.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 48,
        name: "Brooklyn",
        description:
            "Ratione consequatur repudiandae earum, iusto delectus molestiae facilis.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 49,
        name: "Dylan",
        description:
            "Dolorum cumque perspiciatis similique temporibus dolores maxime.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$250.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 50,
        name: "Aurora",
        description: "Aliquam debitis saepe ab ipsa autem beatae.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 51,
        name: "Luke",
        description:
            "Alias magni quisquam at debitis quibusdam asperiores ea soluta optio.",
        status: "paid",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 52,
        name: "Paisley",
        description:
            "Maxime quidem natus error saepe pariatur amet eveniet doloremque quae.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$400.00",
    },
    {
        id: 53,
        name: "Nathan",
        description:
            "Accusantium quam obcaecati, pariatur assumenda numquam vel.",
        status: "paid",
        rate: "$60.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 54,
        name: "Penelope",
        description: "Voluptatibus dolorum id nesciunt veritatis adipisci!",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 55,
        name: "Andrew",
        description:
            "Sapiente nemo magnam possimus laudantium officiis consectetur.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$750.00",
    },
    {
        id: 56,
        name: "Savannah",
        description:
            "Doloribus officiis aspernatur nisi rem aperiam ea optio voluptatum.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 57,
        name: "Elijah",
        description: "Consequatur rem voluptas minus fuga eligendi nulla.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$250.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 58,
        name: "Lila",
        description:
            "Adipisci soluta voluptatem aliquid quam numquam repellat iure.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 59,
        name: "Aiden",
        description:
            "Voluptatem repudiandae officia perferendis exercitationem accusamus veniam.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 60,
        name: "Alyssa",
        description:
            "Harum necessitatibus facilis veritatis distinctio nulla odit.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 61,
        name: "Wyatt",
        description: "Laborum impedit nemo maiores exercitationem facere.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 62,
        name: "Isabella",
        description:
            "Inventore repudiandae suscipit nesciunt harum laboriosam magnam.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 63,
        name: "Ethan",
        description:
            "Eaque ipsa perferendis nesciunt dolor beatae fugit doloremque.",
        status: "due",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 64,
        name: "Grace",
        description: "Ducimus placeat quam dolore explicabo fugit enim.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 65,
        name: "Anthony",
        description: "Voluptate culpa eum facilis quae voluptas.",
        status: "paid",
        rate: "$90.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 66,
        name: "Madeline",
        description: "Fugit magnam distinctio omnis accusantium tenetur.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 67,
        name: "Zachary",
        description: "Praesentium ipsum ex minima quibusdam quod.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 68,
        name: "Samantha",
        description: "Tempore corrupti voluptas commodi architecto distinctio.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 69,
        name: "Christopher",
        description: "Autem velit dolorem pariatur doloribus.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 70,
        name: "Scarlett",
        description: "Aliquid doloribus sit eos commodi accusamus.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 71,
        name: "Joshua",
        description: "Voluptas rerum suscipit eveniet consectetur minima.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 72,
        name: "Victoria",
        description: "Totam molestias voluptatibus fugit dolores earum.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 73,
        name: "Liam",
        description: "Quod voluptatem eos consequuntur repudiandae, sint quia.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 74,
        name: "Aria",
        description:
            "Officia reprehenderit doloribus qui voluptatem, voluptas corporis.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 75,
        name: "Henry",
        description: "Voluptate dolorum fuga explicabo porro.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$250.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 76,
        name: "Ella",
        description: "Repellat accusantium minima alias pariatur ex.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 77,
        name: "Lucas",
        description:
            "Consequatur exercitationem totam eos recusandae sapiente.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 78,
        name: "Luna",
        description:
            "Autem aperiam doloribus consequatur sit fugiat asperiores.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 79,
        name: "James",
        description:
            "Quibusdam laborum officiis deserunt id, similique adipisci.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 80,
        name: "Hannah",
        description: "Quod temporibus maiores architecto dolores nam cumque.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 81,
        name: "Isaac",
        description: "Adipisci doloribus quos non ex repellendus optio.",
        status: "due",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 82,
        name: "Addison",
        description: "Quo voluptatibus deserunt voluptate laudantium suscipit.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 83,
        name: "John",
        description: "Itaque blanditiis veritatis sit doloribus ullam.",
        status: "paid",
        rate: "$90.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 84,
        name: "Zoe",
        description:
            "Beatae asperiores tempore architecto voluptas delectus quasi.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 85,
        name: "Owen",
        description:
            "Voluptatem repudiandae alias nobis deserunt recusandae optio.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 86,
        name: "Lily",
        description: "Sunt dolorem eligendi nisi numquam nulla fuga culpa.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 87,
        name: "Gabriel",
        description:
            "Eius earum reiciendis illum veniam aperiam tempora adipisci.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$300.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 88,
        name: "Natalie",
        description:
            "Cum voluptate voluptatum saepe, unde repellendus laudantium!",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 89,
        name: "Wyatt",
        description:
            "Dignissimos, tempora? Aperiam iste veritatis odit veniam alias.",
        status: "paid",
        rate: "$95.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$700.00",
    },
    {
        id: 90,
        name: "Aubrey",
        description:
            "Repudiandae reprehenderit aspernatur atque officia molestiae veritatis.",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$50.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 91,
        name: "Jack",
        description: "Consequatur rerum impedit nihil quod, officiis libero.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 92,
        name: "Brooklyn",
        description:
            "Ratione consequatur repudiandae earum, iusto delectus molestiae facilis.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 93,
        name: "Dylan",
        description:
            "Dolorum cumque perspiciatis similique temporibus dolores maxime.",
        status: "due",
        rate: "$85.00",
        currency: "CAD",
        balance: "$250.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
    {
        id: 94,
        name: "Aurora",
        description: "Aliquam debitis saepe ab ipsa autem beatae.",
        status: "open",
        rate: "$90.00",
        currency: "CAD",
        balance: "-$150.00",
        phoneNumber: "9877565656",
        deposit: "$600.00",
    },
    {
        id: 95,
        name: "Luke",
        description:
            "Alias magni quisquam at debitis quibusdam asperiores ea soluta optio.",
        status: "paid",
        rate: "$80.00",
        currency: "CAD",
        balance: "-$100.00",
        phoneNumber: "9877565656",
        deposit: "$800.00",
    },
    {
        id: 96,
        name: "Paisley",
        description:
            "Maxime quidem natus error saepe pariatur amet eveniet doloremque quae.",
        status: "open",
        rate: "$85.00",
        currency: "CAD",
        balance: "$200.00",
        phoneNumber: "9877565656",
        deposit: "$400.00",
    },
    {
        id: 97,
        name: "Nathan",
        description:
            "Accusantium quam obcaecati, pariatur assumenda numquam vel.",
        status: "paid",
        rate: "$60.00",
        currency: "CAD",
        balance: "$100.00",
        phoneNumber: "9877565656",
        deposit: "$900.00",
    },
    {
        id: 98,
        name: "Penelope",
        description: "Voluptatibus dolorum id nesciunt veritatis adipisci!",
        status: "due",
        rate: "$65.00",
        currency: "CAD",
        balance: "-$200.00",
        phoneNumber: "9877565656",
        deposit: "$1000.00",
    },
    {
        id: 99,
        name: "Andrew",
        description:
            "Sapiente nemo magnam possimus laudantium officiis consectetur.",
        status: "open",
        rate: "$70.00",
        currency: "CAD",
        balance: "$50.00",
        phoneNumber: "9877565656",
        deposit: "$750.00",
    },
    {
        id: 100,
        name: "Savannah",
        description:
            "Doloribus officiis aspernatur nisi rem aperiam ea optio voluptatum.",
        status: "paid",
        rate: "$75.00",
        currency: "CAD",
        balance: "$150.00",
        phoneNumber: "9877565656",
        deposit: "$500.00",
    },
];
